spring.application.name=store
server.port=8080

# SQL Server - Windows Auth
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=namtrung_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=namtrung
spring.datasource.password=NamTrung@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

# CORS for React dev server
app.cors.allowed-origins=http://localhost:5173
